// presets/react/components/ErrorPage.tsx
/**
 * The React error-page component — a faithful port of the shared DOM contract
 * (.ep-shell / .ep-card / .ep-brand / .ep-status / .ep-title / .ep-message /
 * .ep-actions), driven by the one ErrorPagePayload. Styled by the shared CSS
 * (`@laranail/error-pages-ui/style.css`); the final design lands with the
 * canonical templates. Used by the Inertia and React-SPA stacks.
 */
import type { ErrorPagePayload } from '../../shared/ts/payload';
import { themeClass } from '../../shared/ts/payload';

export function ErrorPage({ page }: { page: ErrorPagePayload }) {
  return (
    <div className={themeClass(page)}>
      <main className="ep-shell" role="main">
        <section className="ep-card">
          <div className="ep-brand">
            {page.brand.logo ? (
              <img className="ep-logo" src={page.brand.logo} alt={page.brand.name} />
            ) : (
              <span className="ep-brand-name">{page.brand.name}</span>
            )}
          </div>
          <p className="ep-status" aria-hidden="true">{page.code}</p>
          <h1 className="ep-title">{page.title}</h1>
          <p className="ep-message">{page.message}</p>
          <div className="ep-actions">
            <a className="ep-btn ep-btn-primary" href={page.homeUrl}>Back to home</a>
          </div>
          {page.requestId ? (
            <p className="ep-ref">
              Reference: <code>{page.requestId}</code>
            </p>
          ) : null}
        </section>
      </main>
    </div>
  );
}

export default ErrorPage;

// presets/vue/ErrorPage.vue
<script setup lang="ts">
/**
 * The Vue error-page component — a faithful port of the shared DOM contract
 * (.ep-shell / .ep-card / .ep-brand / .ep-status / .ep-title / .ep-message /
 * .ep-actions), driven by the one ErrorPagePayload. Styled by the shared CSS
 * (`@laranail/error-pages-ui/style.css`); the final design lands with the
 * canonical templates. Used by the Inertia and Vue-SPA stacks.
 */
import type { ErrorPagePayload } from '../shared/payload';
import { themeClass } from '../shared/payload';

const props = defineProps<{ page: ErrorPagePayload }>();
</script>

<template>
  <div :class="themeClass(props.page)">
    <main class="ep-shell" role="main">
      <section class="ep-card">
        <div class="ep-brand">
          <img v-if="props.page.brand.logo" class="ep-logo" :src="props.page.brand.logo" :alt="props.page.brand.name">
          <span v-else class="ep-brand-name">{{ props.page.brand.name }}</span>
        </div>
        <p class="ep-status" aria-hidden="true">{{ props.page.code }}</p>
        <h1 class="ep-title">{{ props.page.title }}</h1>
        <p class="ep-message">{{ props.page.message }}</p>
        <div class="ep-actions">
          <a class="ep-btn ep-btn-primary" :href="props.page.homeUrl">Back to home</a>
        </div>
        <p v-if="props.page.requestId" class="ep-ref">
          Reference: <code>{{ props.page.requestId }}</code>
        </p>
      </section>
    </main>
  </div>
</template>
